[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "no-cache"
    Content-Type = "application/javascript"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "no-cache"
    Content-Type = "text/css"

[[headers]]
  for = "*.json"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Content-Type = "application/json; charset=utf-8"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
